export const mainCapabilities = [
  {
    title: "Product",
    items: [
      "Discovery",
      "Requirements",
      "Prioritisation",
      "Product Strategy",
      "Portfolio",
      "Business Models",
      "MVP",
      "Stakeholder Alignment",
    ],
  },
  {
    title: "AI",
    items: [
      "Generative AI",
      "RAG",
      "Agentic AI",
      "Machine Learning",
      "NLP",
      "Forecasting",
      "Deep Learning",
    ],
  },
  {
    title: "Platforms",
    items: ["SCADA", "BMS/HVAC", "IoT/IIoT", "Energy", "Edge", "Connected Systems"],
  },
  {
    title: "UX",
    items: [
      "Interaction Design",
      "Figma",
      "User Testing",
      "Accessibility",
      "Heuristic Evaluation",
    ],
  },
];

export const fullCapabilityMap = [
  {
    title: "Product & Strategy",
    items: [
      "Product Management",
      "Product Strategy",
      "Product & Portfolio Strategy",
      "New Product Development",
      "Product Discovery",
      "Requirements Engineering",
      "Requirements Prioritisation",
      "Feature Prioritisation",
      "MVP Definition",
      "Roadmap Contribution",
      "Product Lifecycle Thinking",
      "Value Proposition",
      "Business Models",
      "Go-to-Market",
      "Stakeholder Alignment",
      "Technical-commercial trade-offs",
    ],
  },
  {
    title: "AI & Data",
    items: [
      "AI-enabled products",
      "GenAI / LLMs",
      "RAG",
      "GraphRAG",
      "Agentic AI",
      "Multi-Agent Systems",
      "Machine Learning",
      "Deep Learning",
      "NLP",
      "Predictive Analytics",
      "Time-Series Forecasting",
      "Probabilistic Forecasting",
      "Computer Vision",
      "Data-Driven Decision Support",
    ],
  },
  {
    title: "Industrial / Platform",
    items: [
      "Industrial Digital Platforms",
      "SCADA",
      "BMS",
      "HVAC",
      "EMS",
      "Building Automation",
      "PLC",
      "IoT",
      "IIoT",
      "OPC UA",
      "Edge Systems",
      "Connected Systems",
      "Industrial Communication",
      "Real-Time Monitoring",
      "Energy Systems",
      "Smart Buildings",
      "Mission-Critical Environments",
    ],
  },
  {
    title: "UX / Discovery",
    items: [
      "Customer Discovery",
      "User Needs",
      "Interaction Design",
      "Wireframing",
      "Paper Prototyping",
      "Figma",
      "User Testing",
      "Accessibility",
      "Inclusive Design",
      "Heuristic Evaluation",
    ],
  },
  {
    title: "Tools",
    items: [
      "Python",
      "PyTorch",
      "Scikit-learn",
      "LangChain",
      "LangGraph",
      "LangSmith",
      "RAGAS",
      "Transformers",
      "PEFT",
      "LoRA",
      "SQL",
      "NoSQL",
      "Graph Databases",
      "Knowledge Graphs",
      "Vector Databases",
      "Time-Series Data",
    ],
  },
];

export const capabilityNote =
  "Depth varies across these areas — they are shown as working familiarity, not equal expert-level mastery.";
